# Generated by Django 4.1.6 on 2023-04-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_pic',
            field=models.ImageField(default='/profilepics/default.jpeg', upload_to='images/cover_pic'),
        ),
    ]
